# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ASUS/Desktop/PLD/battle/battle.cache/wt [current_project]
set_property parent.project_path C:/Users/ASUS/Desktop/PLD/battle/battle.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ASUS/Desktop/PLD/battle/battle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/ASUS/Desktop/PLD/program_v090/lab2_6/VGA_ctler/VGA_ctler.srcs/test_240_160.coe
read_verilog -library xil_defaultlib {
  C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/new/LED.v
  C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/imports/VGA_ctler/clk_div.v
  C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/imports/VGA_ctler/vga_bsprite.v
  C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/imports/VGA_ctler/vga_core.v
  C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/new/VGA_ctler.v
}
read_ip -quiet C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/constrs_1/new/TOP.xdc
set_property used_in_implementation false [get_files C:/Users/ASUS/Desktop/PLD/battle/battle.srcs/constrs_1/new/TOP.xdc]


synth_design -top VGA_ctler -part xc7a35tcpg236-1


write_checkpoint -force -noxdef VGA_ctler.dcp

catch { report_utilization -file VGA_ctler_utilization_synth.rpt -pb VGA_ctler_utilization_synth.pb }
