#clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

#switch signal
set_property PACKAGE_PIN V17 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports clr]


set_property PACKAGE_PIN W19 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property PACKAGE_PIN T18 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property PACKAGE_PIN T17 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property PACKAGE_PIN U17 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property PACKAGE_PIN U18 [get_ports {key[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[4]}]

#
set_property PACKAGE_PIN V16 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN W16 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property PACKAGE_PIN W17 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property PACKAGE_PIN W15 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property PACKAGE_PIN V15 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property PACKAGE_PIN W14 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property PACKAGE_PIN W13 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property PACKAGE_PIN V2 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]

#


# VGA signals
set_property PACKAGE_PIN J18 [get_ports {blu[3]}]
set_property PACKAGE_PIN K18 [get_ports {blu[2]}]
set_property PACKAGE_PIN L18 [get_ports {blu[1]}]
set_property PACKAGE_PIN N18 [get_ports {blu[0]}]
set_property PACKAGE_PIN D17 [get_ports {grn[3]}]
set_property PACKAGE_PIN G17 [get_ports {grn[2]}]
set_property PACKAGE_PIN H17 [get_ports {grn[1]}]
set_property PACKAGE_PIN J17 [get_ports {grn[0]}]
set_property PACKAGE_PIN N19 [get_ports {red[3]}]
set_property PACKAGE_PIN J19 [get_ports {red[2]}]
set_property PACKAGE_PIN H19 [get_ports {red[1]}]
set_property PACKAGE_PIN G19 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blu[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blu[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blu[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blu[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {grn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {grn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {grn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {grn[0]}]
set_property PACKAGE_PIN P19 [get_ports hs]
set_property PACKAGE_PIN R19 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]



set_property PACKAGE_PIN U7 [get_ports {seg[0]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]
set_property PACKAGE_PIN W7 [get_ports {seg[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

set_property PACKAGE_PIN W4 [get_ports {enable_n[3]}]
set_property PACKAGE_PIN V4 [get_ports {enable_n[2]}]
set_property PACKAGE_PIN U4 [get_ports {enable_n[1]}]
set_property PACKAGE_PIN U2 [get_ports {enable_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_n[0]}]

